#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------


layout(std430, binding = 3) buffer SpatialBuffer {
    ivec2 spatial[];
};

uniform int j;
uniform int k;


// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------


void main() {
	uint i = gl_GlobalInvocationID.x;

	int l = int(i) ^ j;
	if (l > i) {
		if ((i & k) == 0 && spatial[i].x > spatial[l].x || (i & k) != 0 && spatial[i].x < spatial[l].x) {
			ivec2 tmp = spatial[i];
			spatial[i] = spatial[l];
			spatial[l] = tmp;
		}
	}
}
