#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------

struct Particle {
	vec3 position;
	vec3 predicted_position;
	vec3 velocity;
	float density;
	float near_density;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------

void main() {
	float gravity_strength = 10.0;
	float delta_time = 1.0 / 60.0;
	uint id = gl_GlobalInvocationID.x;
	particles[id].velocity += vec3(0.0, -1.0, 0.0) * gravity_strength * delta_time;
	particles[id].predicted_position = particles[id].position + particles[id].velocity * delta_time;



}
