#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------


layout(std430, binding = 3) buffer SpatialBuffer {
    ivec2 spatial[];
};

layout(std430, binding = 4) buffer StartBuffer {
    int start_inds[];
};


// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------


void main() {
	uint id = gl_GlobalInvocationID.x;
	if (id == 0 || spatial[id].x != spatial[id - 1].x) {
		start_inds[spatial[id].x] = int(id);
	}
}
