#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------

struct Particle {
	vec3 position;
	vec3 predicted_position;
	vec3 velocity;
};

struct ViscosityForce {
	vec3 force;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(std430, binding = 5) buffer ViscosityForcesBuffer {
    ViscosityForce viscosity_forces[];
};

uniform float delta_time;


// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------


void main() {
	uint id = gl_GlobalInvocationID.x;

	particles[id].velocity += viscosity_forces[id].force * delta_time;
}
